versions_path: '\\SRV\PNDatabases\File Aechive ENC' # Путь к папкам с версиями ПО на сервере
server_program_path: '\\SRV\PNPrograms\File Archive' # Путь к программе на сервере

program_name: 'File Archive' # Наименование программы
program_version_number: '4.0.0' # Версия программы

password: '202020' # Пароль для доступа к функциям добавления и удаления