versions_path: '' # Path to the folders with software versions on the server
server_program_path: '' # Path to the File Archive program on the server

program_name: 'File Archive' # Program name
program_version_number: '4.0.0' # Program version